### PR TITLE
Adding a new theme electro

### PR DESCRIPTION
**Pull request by eksoparty**
Please try it out, I think you will like it. :)

### CODE REVIEW

**Comment by ghost** [comment]
Give us some preview bro :)

**Comment by eksoparty** [comment]
iTerm 2 theme : materialshelldark.
Zsh theme: materialshellelectro.
screen shot 2016-09-08 at 7 58 14 pm

iTerm 2 theme : materialshelloceanic.
Zsh theme: materialshellelectro.
screen shot 2016-09-08 at 7 59 17 pm

P.S. I am using Source Code Pro font.

**Comment by ghost** [comment]
Merge this! 😄  @carloscuesta

**Comment by carloscuesta** [comment]
Looks good @xitkov thanks for sending the pull request 👍

**Pull request merged**
